name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        # The name of the image you would like to push
        name: pruebasacr.azurecr.io/eshopwebmvc
        # The login username for the registry
        username: ${{ secrets.ACR_USERNAME }}
        # The login password for the registry
        password: ${{ secrets.ACR_PASSWORD }}
        # Use registry for pushing to a custom registry
        registry: ${{ secrets.ACR_REGISTRY }}
        # Use dockerfile when you would like to explicitly build a Dockerfile
        dockerfile: ./src/Web/Dockerfile

  deploy:
    needs: build
    name: Deploy App
    runs-on: ubuntu-latest
    
    steps:
    - name: deploy to azure web app
      uses: azure/appservice-actions/webapp@master
      with: 
        app-name: mynewestwebapplication
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
